### ISSUE TITLE
Site que está no ar não está funcionando!

### ISSUE THREAD

**Issue by Logikoz** [Tsugami/Softwrap#2]
Tentei fazer o fluxo padrão do teste, porém tive problema em:

- Buscar um um usuário pela barra de pesquisa!
- Adicionar um novo usuário

Logo, não consegui concluir meus testes!

Creio que não faça sentido um SPA fazer requisição para o `localhost`
![image](https://user-images.githubusercontent.com/37851168/101712453-8dcb0d00-3a63-11eb-901a-aa891ea6c490.png)

Se possível, realizar as correção dos problemas citados para rever o fluxo inteiro, e partir para o code-review!

Fico no aguardo!

**Comment by Tsugami** [comment]
@Logikoz arrumei! https://softwrap.vercel.app/

**Comment by Tsugami** [comment]
Não estava conseguindo upar o arquivo de autenticação no servidor. troquei a biblioteca `firebase-admin` para `firebase` e consegui fazer autenticação por chave!

**Comment by Tsugami** [comment]
@Logikoz , vou arquivar o repositório, ainda quer testar?

**Comment by Logikoz** [comment]
É irrelevante agora 😂

**Comment by Tsugami** [comment]
kkkkkk
